apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: weekly-grouse-java-quarkus 
  janus-idp.io/tekton: weekly-grouse-java-quarkus
  backstage.io/kubernetes-id: weekly-grouse-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: weekly-grouse-java-quarkus
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  